### ISSUE TITLE
Custom categories for sources instead of just Pinned/All

### ISSUE THREAD

**Issue by JoeloJoestar** [komikku-app/komikku#118] opened 2024-06-26 05:19 UTC
### Describe your suggested feature

Making source/extension categories much more useful, instead of only having the option to search new manga from either **Pinned** or **All** why not by source categories too?
I have those for safe ones, hentai, Korean, western... I wish I could search Manga on group by source category.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.10.5](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fellinir** [comment] 2024-06-28 00:11
I think this might be a duplicate of issue #72. If so we can close it

**Comment by NeKoOuO** [comment] 2024-08-09 00:17
Yes it's same issue

**Closed** 2024-08-09 01:03 UTC
Labels: enhancement
