### ISSUE TITLE
Group Updated Chapters Together

### ISSUE THREAD

**Issue by ArchCelestial** [komikku-app/komikku#246] opened 2024-08-10 00:30 UTC
### Describe your suggested feature

In the updates screen, if there is multiple chapters of a work that were newly added, they should all be under one title that can be clicked for a drop-down to see the individual new chapters, just like Yokai and Tachij2k had.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.11.2](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kana-shii** [comment] 2024-08-10 00:40
Duplicate of #64

**Closed** 2024-08-10 14:56 UTC
