### ISSUE TITLE
Add a toggle to make a manga Lewd or not Lewd regardless of tags

### ISSUE THREAD

**Issue by Idontloveanyone** [komikku-app/komikku#552] opened 2024-11-22 15:43 UTC
### Describe your suggested feature

Some mangas are considered lewd because of some tags, even though they aren't really... Like Berserk for example. Some are super lewd but don't have the right tag so I have to go add the tag adult or mature manually.

Instead, being able to set a manga as lewd (or not) would be awesome!

Also it would be even better to be able to select multiple mangas and do it, instead of doing one by one...

Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/komikku-app/extensions/issues/new/choose).
- [X] I have updated the app to version **[1.12.1](https://github.com/komikku-app/komikku/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vvirtues** [comment] 2024-12-10 00:33
think this is a duplicate of https://github.com/komikku-app/komikku/issues/205

**Comment by cuong-tran** [comment] 2024-12-12 15:38
why don't use Hidden categories?

**Closed** 2024-12-12 15:39 UTC
